# Generated by Django 3.0.3 on 2020-08-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/competitions')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=False)),
                ('about', models.TextField()),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
    ]
